### ISSUE TITLE
$.javascript examples

### ISSUE THREAD

**Issue by merlinpatt** [raix/Meteor-handlebar-helpers#58]
Can you add some docs / examples on the $.javascript helper?

The other helpers are fairly straightforward but I'm not sure what can or can't be used with $.javascript.

Can I do {{$.javascript Session.get('someKey').length}}?
Can I do {{$.javascript console.log('someLog')}}?
Can I do {{$.javascript Session.set('someKey', 'someValue')}}?

**Comment by serkandurusoy** [comment]
That part of the documentation may be cryptic at first. What it means is, there is a new `$` helper, whose scope can be extended with any javascript function or namespace object you can directly access.

`Meteor` and `Session` are already in that scope so that not only you could do `{{$.Session.get 'someSessionKey'}}` or `{{$.Meteor.isCordova}}` but you could also 

```javascript
testCollection = new Meteor.Collection('test');
testCollection.insert({name: 'test 1', createdAt: new Date()})
Helpers.addScope('testCollection', testCollection);
```

```handlebars
{{#each $.testCollection.find}}
  	{{name}} - timeStamp: {{createdAt}}<br/>
{{/each}}
```

**Comment by serkandurusoy** [comment]
@merlinpatt I'm guessing your question has been answered. Please make not if you need further assistance.
