### ISSUE TITLE
Feature Request: isActive

### ISSUE THREAD

**Issue by derwaldgeist** [raix/Meteor-handlebar-helpers#62]
Some frameworks use an 'active' class to signal something is in an active state. It would be nice to have such a helper like isSelected and isChecked.

BTW: I tried the isChecked helper in a class="" attribute, together with a nested expression, like this:

```html
<div class="{{isSelected instance.acceptance.get 'yes'}}">
```
This did not work, instead of 'selected' I got '[object Object]'.

The same expression worked inside an #if $eq:

```html
{{#if $eq instance.acceptance.get "yes"}}
```
Any ideas why the attribute variant did not work?

**Comment by filipenevola** [comment]
I have this implemented, very simple, can I submit a pull request for that?

**Comment by serkandurusoy** [comment]
There was a similar discussion previousy and if I am not mistaken @raix was pro keeping this simple since the nested expression syntax with paranthesis (that's introduced with meteor 1.2) would be sufficient in most cases, combined with one of the other helpers provided.

**Comment by filipenevola** [comment]
But what is the difference between this and isSelected and isChecked? 

@raix what do you think about that?

**Comment by serkandurusoy** [comment]
@derwaldgeist the reason you get an object is that these two helpers return an object and they are not intended to return style classes, but are designed to return html properties

so the returning `{ selected: 'selected' }` translates into `selected` property of the tag. and is not intended for use with a `div`, but rather for select, checkbox and radio controls.

@filipenevola I think this answers your question as well since there is no html property named `active`

**Comment by derwaldgeist** [comment]
> are designed to return html properties

OK, understood, makes sense!

**Comment by filipenevola** [comment]
Hi @serkandurusoy and @raix  . I can understand your point but I can't understand why is bad to have a helper like isActive? I got it is different from others but everything need to be the same? 

The purpose is to have helpers or to have html properties producers?

I think you can be more flexible and add more value to your package or clarify in README what is the purpose of this and with that information people can choose create new package with helpers to complement this one.

Sorry if I'm missing some point or being a pain in the ass but I want to understand well to have a better expectation about this package.

**Comment by serkandurusoy** [comment]
Oh no way you are a pain, you are not. I can't speak on behalf of @raix and he is the "owner" of this package. I just offered a hand and he graciously accepted it, that's why I'm here making so much noise.

Since I've spent some time reading the issues and his earlier replies, I kind of have an understanding how he thinks about this package.

Let's wait to hear what he actually has to say.

**Comment by raix** [comment]
I agree with @serkandurusoy,

 `isChecked` and `isSelected` are html standard helpers, eg.:
```html
  <input type="checkbox" name="foo" value="bar" {{isChecked true}}>
```

-

`isActive` is a custom thing,
> "Some frameworks use an 'active' class"

Who is going to decide if it's "active" / "current" etc.?

-

I guess you could have a helper like:
```
  <div class="{{is "active" true}}">foo</div>
  <div class="{{is "current" $eq 1 1}}">foo</div>

  <div class="{{isNot "active" true}}">foo</div>
```

but it might be easier to write the helper instead, these are often more complicated in terms of filtering etc. opinions?

**Comment by filipenevola** [comment]
Hi @raix , I liked your suggestion.

Can I procced with a PR with this?

**Comment by raix** [comment]
@filipenevola ok
