### ISSUE TITLE
How can i use {{$eq}} as condition?

### ISSUE THREAD

**Issue by frozeman** [raix/Meteor-handlebar-helpers#9]
i didnt found anything in the code, but using
  
     {{$eq myVar "test"}}
      Show this text
     {{/$eq}}

doesn't work, but would be the expected behavior IMHO.

**Comment by serkandurusoy** [comment]
@frozeman `$eq myVar "test"` itself returns `true/false` and it is up to you to decide how to use that return value. If you want to use that to hide/display a block, than you an feed that to a block helper like `#if` as suggested.

I'm closing this now since that this is now 2 years old :) But let us know if you have further questions.
